######################################################################
# Automatically generated by qmake (3.0) Wed Jan 27 21:32:38 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 24hr-relay
INCLUDEPATH += .

# Input
SOURCES += qttest.cpp
