######################################################################
# Automatically generated by qmake (3.0) Thu Jan 28 09:16:41 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = main
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += main.cpp
SOURCES += timesDisplay.cpp
SOURCES += totalTime.cpp

HEADERS += timesDisplay.h
HEADERS += totalTime.h
